// import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>This is a header for every page!</header>
        <nav>
          <Link href="/">Home</Link>
          <Link href="/about">About</Link>
          <Link href="/post/1">Post</Link>
          <Link href="/posts">Posts</Link>
        </nav>
        {children}
        <footer>This is a footer for every page!</footer>
      </body>
    </html>
  );
}
